FIELD_ALIASES: dict[str, tuple[str, str]] = {
    "TEST.TSTNO": ("tests", "test_no"),
    "TEST.TSTDAT": ("tests", "test_date_raw"),
    "TEST.TSTPRFD": ("tests", "test_performer"),
    "TEST.TSTCFND": ("tests", "test_configuration"),
    "TEST.CLSSPD": ("tests", "closing_speed_raw"),
    "VEHICLE.MAKED": ("vehicles", "make"),
    "VEHICLE.MODELD": ("vehicles", "model"),
    "VEHICLE.YEAR": ("vehicles", "model_year"),
    "VEHICLE.VEHSPD": ("vehicles", "vehicle_speed_raw"),
    "BARRIER.BARRIGD": ("barriers", "rigidity"),
    "BARRIER.BARSHPD": ("barriers", "shape"),
    "BARRIER.BARANG": ("barriers", "angle_raw"),
    "OCCUPANT.OCCLOC": ("occupants", "occupant_location_raw"),
    "OCCUPANT.OCCTYPD": ("occupants", "occupant_type"),
    "OCCUPANT.HIC": ("injury_metrics", "metric_code"),
    "API.testNo": ("tests", "test_no"),
    "API.testDate": ("tests", "test_date_raw"),
    "API.testType": ("tests", "test_type"),
    "API.testConfiguration": ("tests", "test_configuration"),
    "API.closingSpeed": ("tests", "closing_speed"),
    "API.vehicleMake": ("vehicles", "make"),
    "API.vehicleModel": ("vehicles", "model"),
    "API.modelYear": ("vehicles", "model_year"),
    "API.rigidOrDeformableBarrier": ("barriers", "rigidity"),
    "API.barrierShape": ("barriers", "shape"),
    "API.sensorType": ("instrumentation_channels", "sensor_type"),
    "API.axisDirofSensor": ("instrumentation_channels", "sensor_axis"),
    "instrumentation_info.axisDirofSensor": ("instrumentation_channels", "sensor_axis"),
    "instrumentation_info.curveNo": ("instrumentation_channels", "curve_no"),
    "instrumentation_info.dataMeasurementUnits": ("instrumentation_channels", "unit_raw"),
    "instrumentation_info.dataStatus": ("instrumentation_channels", "data_status"),
    "instrumentation_info.instrumentationCommentary": (
        "instrumentation_channels",
        "extra_json",
    ),
    "instrumentation_info.numberofFirstPoint": ("instrumentation_channels", "first_point"),
    "instrumentation_info.numberofLastPoint": ("instrumentation_channels", "last_point"),
    "instrumentation_info.sensorAttachment": (
        "instrumentation_channels",
        "sensor_attachment",
    ),
    "instrumentation_info.sensorLocation": ("instrumentation_channels", "sensor_location"),
    "instrumentation_info.sensorType": ("instrumentation_channels", "sensor_type"),
    "instrumentation_info.timeIncrement": ("instrumentation_channels", "time_increment"),
    "instrumentation_info.channelStatus": ("instrumentation_channels", "channel_status"),
    "occupant_info.vehicleNo": ("occupants", "source_vehicle_no"),
    "occupant_info.occupantLocation": ("occupants", "occupant_location_raw"),
    "occupant_info.occupantType": ("occupants", "occupant_type"),
    "occupant_info.dummyType": ("occupants", "dummy_type"),
    "restraint_info.vehicleNo": ("restraints", "source_vehicle_no"),
    "restraint_info.occupantLocation": ("restraints", "occupant_location_raw"),
    "restraint_info.restraintType": ("restraints", "restraint_type"),
    "restraint_info.inflationer": ("restraints", "deployment_status"),
    "restraint_info.BeltPretensionerDeployment": ("restraints", "deployment_status"),
    "vehicle_info.vehicleNo": ("vehicles", "source_vehicle_no"),
    "vehicle_info.vehicleMake": ("vehicles", "make"),
    "vehicle_info.vehicleModel": ("vehicles", "model"),
    "vehicle_info.modelYear": ("vehicles", "model_year"),
    "vehicle_info.vehicleSpeed": ("vehicles", "vehicle_speed_raw"),
    "vehicle_info.vehicleTestWeight": ("vehicles", "vehicle_test_weight_raw"),
    "barrier_info.rigidOrDeformableBarrier": ("barriers", "rigidity"),
    "barrier_info.barrierShape": ("barriers", "shape"),
    "barrier_info.angleofFixedBarrier": ("barriers", "angle_raw"),
    "barrier_info.testNo": ("tests", "test_no"),
}
